# Generated by Django 5.2.7 on 2025-10-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Ism')),
                ('lastname', models.CharField(max_length=50, verbose_name='Familiya')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Otasining ismi')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Vazn (kg)')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Bo‘y (sm)')),
                ('birth_year', models.PositiveSmallIntegerField(verbose_name='Tug‘ilgan yil')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='athlete_pictures/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Sportchi',
                'verbose_name_plural': 'Sportchilar',
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Sport turi nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Sport turi',
                'verbose_name_plural': 'Sport turlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_heart_rate', models.PositiveSmallIntegerField(verbose_name='Mashg‘ulotdan oldingi yurak urishi (bpm)')),
                ('post_heart_rate', models.PositiveSmallIntegerField(verbose_name='Mashg‘ulotdan keyingi yurak urishi (bpm)')),
                ('exercise_count', models.PositiveSmallIntegerField(verbose_name='Mashqlar soni')),
                ('duration_seconds', models.PositiveIntegerField(verbose_name='Mashg‘ulot davomiyligi (sekundda)')),
                ('file', models.FileField(blank=True, null=True, upload_to='training_files/', verbose_name='Qo‘shimcha fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='core.athlete', verbose_name='Sportchi')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.sporttype', verbose_name='Sport turi')),
            ],
            options={
                'verbose_name': 'Mashg‘ulot',
                'verbose_name_plural': 'Mashg‘ulotlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
