# Generated by Django 5.2.7 on 2025-10-15 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Sportchi darajasi nomi')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Daraja raqami')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Sportchi darajasi',
                'verbose_name_plural': 'Sportchi darajalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Lotincha nomi')),
                ('title', models.CharField(max_length=50, verbose_name="O'zbekcha nomi")),
                ('shortname', models.CharField(max_length=16, verbose_name='Qisqa nomi')),
                ('model_url', models.TextField(verbose_name='AI Model manzili')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Muskul',
                'verbose_name_plural': 'Muskullar',
            },
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Sport turi nomi')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Daraja raqami')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Sport turi',
                'verbose_name_plural': 'Sport turlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Ism')),
                ('lastname', models.CharField(max_length=50, verbose_name='Familiya')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Otasining ismi')),
                ('birth_year', models.PositiveSmallIntegerField(verbose_name='Tug‘ilgan yil')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='athlete_pictures/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete', to='core.athletelevel')),
            ],
            options={
                'verbose_name': 'Sportchi',
                'verbose_name_plural': 'Sportchilar',
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='AthleteParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField(default=0)),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Vazn (kg)')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Bo‘y (sm)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='core.athlete')),
            ],
            options={
                'verbose_name': 'Sportchi parametrlari',
                'verbose_name_plural': 'Sportchilar parametrlari',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name="Mashg'ulot nomi")),
                ('pre_heart_rate', models.PositiveSmallIntegerField(default=0, verbose_name='Mashg‘ulotdan oldingi yurak urishi (bpm)')),
                ('post_heart_rate', models.PositiveSmallIntegerField(default=0, verbose_name='Mashg‘ulotdan keyingi yurak urishi (bpm)')),
                ('exercise_count', models.PositiveSmallIntegerField(default=0, verbose_name='Mashqlar soni')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Mashg‘ulot davomiyligi (millisekundda)')),
                ('file_EMT', models.FileField(blank=True, null=True, upload_to='training_files/', verbose_name='EMT fayl')),
                ('file_ECG', models.FileField(blank=True, null=True, upload_to='training_files/', verbose_name='ECG fayl')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='core.athlete', verbose_name='Sportchi')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to='core.sporttype', verbose_name='Sport turi')),
            ],
            options={
                'verbose_name': 'Mashg‘ulot',
                'verbose_name_plural': 'Mashg‘ulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_count', models.PositiveSmallIntegerField(default=0, verbose_name="Boshlang'ich vaqt")),
                ('last_count', models.PositiveSmallIntegerField(default=0, verbose_name='Yakuniy vaqt')),
                ('signal_length', models.PositiveBigIntegerField(default=-1, verbose_name='Mashq davomiyligi (millisekund)')),
                ('hrate', models.PositiveSmallIntegerField(default=-1, verbose_name='Yurak urishi')),
                ('fatigue', models.FloatField(default=-1, verbose_name='Charchoq qiymati')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execise', to='core.trainingsession')),
            ],
            options={
                'verbose_name': 'Mashq',
                'verbose_name_plural': 'Mashqlar',
            },
        ),
    ]
