# Generated by Django 5.2.7 on 2025-10-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='duration_seconds',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Mashg‘ulot davomiyligi (millisekundda)'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='exercise_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Mashqlar soni'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='post_heart_rate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Mashg‘ulotdan keyingi yurak urishi (bpm)'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='pre_heart_rate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Mashg‘ulotdan oldingi yurak urishi (bpm)'),
        ),
    ]
