# Generated by Django 5.2.7 on 2025-10-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='fatigue',
            field=models.FloatField(default=0, verbose_name='Charchoq qiymati'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='hrate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Yurak urishi'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='signal_length',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Mashq davomiyligi (millisekund)'),
        ),
    ]
