# Generated by Django 5.2.7 on 2025-10-18 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_exercise_fatigue_alter_exercise_hrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='fatigue',
        ),
        migrations.CreateModel(
            name='MuscleFatigue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatigue', models.FloatField(default=0, verbose_name='Charchoq qiymati')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle_fatigue', to='core.exercise')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatigues', to='core.muscle')),
            ],
            options={
                'verbose_name': "Muskul charchog'i",
                'verbose_name_plural': 'Muskul charchoqlari',
            },
        ),
    ]
