# Generated by Django 5.2.7 on 2025-11-20 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_exercise_fatigue_musclefatigue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='athleteparams',
            name='height',
            field=models.FloatField(verbose_name='Bo‘y (sm)'),
        ),
        migrations.AlterField(
            model_name='athleteparams',
            name='weight',
            field=models.FloatField(verbose_name='Vazn (kg)'),
        ),
    ]
